AitamIndexBundle:
    resource: "@AitamIndexBundle/Resources/config/routing.yml"
    prefix:   /
AitamIndexBundle_homepage:
    pattern:  /
    defaults: { _controller: AitamIndexBundle:Page:index }
    requirements:
        _method:  GET
EnricoBlogBundle:
    resource: "@EnricoBlogBundle/Resources/config/routing.yml"
    prefix:   /       
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
