AitamIndexBundle_homepage:
    pattern:  /index
    defaults: { _controller: AitamIndexBundle:Page:index }
    requirements:
        _method:  GET

AitamIndexBundle_contact:
    pattern:  /contact
    defaults: { _controller: AitamIndexBundle:Page:contact }
    requirements:
        _method:  GET|POST
        
AitamIndexBundle_about:
    pattern:  /about
    defaults: { _controller: AitamIndexBundle:Page:about }
    requirements:
        _method:  GET 
        
AitamIndexBundle_statuto:
    pattern:  /statuto
    defaults: { _controller: AitamIndexBundle:Page:statuto }
    requirements:
        _method:  GET  
        
AitamIndexBundle_progetti:
    pattern:  /progetti
    defaults: { _controller: AitamIndexBundle:Page:progetti }
    requirements:
        _method:  GET 
        
AitamIndexBundle_dinuovo_show:
    pattern:  /{id}
    defaults: { _controller: AitamIndexBundle:Dinuovo:dinuovo }
    requirements:
        _method:  GET
        id: \d+

AitamIndexBundle_home_dinuovo:
    pattern:  /home_dinuovo
    defaults: { _controller: AitamIndexBundle:Dinuovo:home_dinuovo }
    requirements:
        _method:  GET              