<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120804211945 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE dinuovo_audit (id INT NOT NULL, rev INT NOT NULL, title VARCHAR(255) DEFAULT NULL, author VARCHAR(100) DEFAULT NULL, articolo LONGTEXT DEFAULT NULL, image VARCHAR(20) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE blog_audit");
        $this->addSql("ALTER TABLE dinuovo ADD path VARCHAR(255) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE blog_audit (id INT NOT NULL, rev INT NOT NULL, slug VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, author VARCHAR(100) DEFAULT NULL, blog LONGTEXT DEFAULT NULL, image VARCHAR(20) DEFAULT NULL, tags LONGTEXT DEFAULT NULL, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev)) ENGINE = InnoDB");
        $this->addSql("DROP TABLE dinuovo_audit");
        $this->addSql("ALTER TABLE dinuovo DROP path");
    }
}
